class AddBreeds < ActiveRecord::SeedMigration
  def self.up
    breeds = [
      'Ameraucana',
      'Ancona',
      'Andalusian',
      'Appenzeller Spitzhauben',
      'Araucana',
      'Aseel',
      'Australorp',
      'Barnevelder',
      'Belgian Bearded d\'Uccle Bantam',
      'Booted Bantam',
      'Brahma',
      'Calico Princess',
      'Campine',
      'Catalana',
      'Chantecler',
      'Cochin',
      'Cornish',
      'Crevecoeur',
      'Cubalaya',
      'Deleware',
      'Dominique',
      'Dorking',
      'Easter Egger',
      'Faverolles',
      'Fayoumi',
      'Golden Comet Chicken',
      'Hamburg',
      'Holland',
      'Houdan',
      'Japanese Bantam',
      'Java',
      'Jersey Giant',
      'La Fleche',
      'Lakenvelder',
      'Langshan',
      'Leghorn',
      'Malay',
      'Malaysian Serama',
      'Marans',
      'Minorca',
      'Modern Game',
      'Naked Neck',
      'New Hampshire Red',
      'Old English Game',
      'Orpington',
      'Penedesenca',
      'Phoenix',
      'Plymouth Rock',
      'Polish',
      'Redcap',
      'Rhode Island Red',
      'Rosecomb',
      'Russian Orloff',
      'Sebright',
      'Sicilian Buttercup',
      'Silkie Chicken',
      'Star',
      'Sultan',
      'Sumatra',
      'Sussex',
      'Welsummer',
      'White-Faced Black Spanish',
      'Wyandotte',
      'Yokohama',
      'Other'
    ]

    breeds.each do |breed|
      Breed.create(name: breed) unless Breed.exists?(name: breed)
    end
  end
end
